[2025-09-16T14:12:08.162+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-16T14:12:08.194+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nakhonpathom_waste_csv_etl_dag.load_data_to_db manual__2025-09-16T14:11:56.517190+00:00 [queued]>
[2025-09-16T14:12:08.205+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nakhonpathom_waste_csv_etl_dag.load_data_to_db manual__2025-09-16T14:11:56.517190+00:00 [queued]>
[2025-09-16T14:12:08.207+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-16T14:12:08.225+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_to_db> on 2025-09-16 14:11:56.517190+00:00
[2025-09-16T14:12:08.235+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=178) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-16T14:12:08.237+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nakhonpathom_waste_csv_etl_dag', 'load_data_to_db', 'manual__2025-09-16T14:11:56.517190+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/hazardous_waste_etl_dag.py', '--cfg-path', '/tmp/tmptbi4cmax']
[2025-09-16T14:12:08.238+0000] {standard_task_runner.py:63} INFO - Started process 180 to run task
[2025-09-16T14:12:08.239+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask load_data_to_db
[2025-09-16T14:12:08.302+0000] {task_command.py:426} INFO - Running <TaskInstance: nakhonpathom_waste_csv_etl_dag.load_data_to_db manual__2025-09-16T14:11:56.517190+00:00 [running]> on host 29fe93b12185
[2025-09-16T14:12:08.440+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nakhonpathom_waste_csv_etl_dag' AIRFLOW_CTX_TASK_ID='load_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2025-09-16T14:11:56.517190+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-16T14:11:56.517190+00:00'
[2025-09-16T14:12:08.442+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-16T14:12:08.536+0000] {logging_mixin.py:188} INFO - Success: Loaded 347 records to table 'hazardous_waste'.
[2025-09-16T14:12:08.538+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-09-16T14:12:08.541+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-16T14:12:08.558+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=nakhonpathom_waste_csv_etl_dag, task_id=load_data_to_db, run_id=manual__2025-09-16T14:11:56.517190+00:00, execution_date=20250916T141156, start_date=20250916T141208, end_date=20250916T141208
[2025-09-16T14:12:08.615+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-16T14:12:08.645+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-16T14:12:08.670+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
